owner: CampLegal
repo: camplegal-status

sites:
  - name: Lawyer Portal
    url: https://lawyer.camplegal.com/
  - name: Customer Portal
    url: https://client.camplegal.com/
  - name: Corp Portal
    url: https://corp.camplegal.com/
  - name: API
    url: https://api.camplegal.com/api/v1/mobile/ping
    expectedStatusCodes:
      - 200
      - 201


status-website:
  cname: status.camplegal.com
  logoUrl: https://d160bvpqb05zv9.cloudfront.net/microsoft-add-in/assets/CampLegal32.png
  name: CampLegal Status
  introTitle: "**CampLegal** System Status"
  introMessage: Current status of CampLegal services. Updated every 5 minutes.
  navbar:
    - title: Homepage
      href: https://camplegal.com
    - title: Support
      href: mailto:support@camplegal.com
