owner: camplegal-llc
repo: camplegal-status

sites:
  - name: Lawyer Portal
    url: https://lawyer.camplegal.com/
  - name: Customer Portal
    url: https://client.camplegal.com/login
  - name: Corp Portal
    url: https://corp.camplegal.com/login
  - name: API
    url: https://api.camplegal.com/api/v1/mobile/ping
    expectedStatusCodes:
      - 200
      - 201


status-website:
  publish: true
  cname: status.camplegal.com
  logoUrl: https://d160bvpqb05zv9.cloudfront.net/microsoft-add-in/assets/CampLegal32.png
  name: CampLegal Status
  introTitle: "**CampLegal** System Status"
  introMessage: Current status of CampLegal services. Updated every 5 minutes.
  navbar:
    - title: Homepage
      href: https://camplegal.com
    - title: Support
      href: mailto:support@camplegal.com

workflowSchedule:
  graphs: "0 0 * * *"      # Daily graphs update
  responseTime: "0 23 * * *"  # Response time check
  staticSite: "0 1 * * *"   # Rebuild site daily
  summary: "0 0 * * *"      # Daily summary
  updateTemplate: "0 0 * * *"
  updates: "*/5 * * * *"    # Check every 5 minutes
  uptime: "*/5 * * * *"     # Uptime check every 5 minutes
  
